application:
  name: MindMark
  version: 1.0.0-SNAPSHOT
  copyright-year: 2024
  demo-enabled: true
  address-enabled: true
  page-size: 15                           #???????????????????????
  watch-file:
    enabled: true                         #?????????????????????????????????
    file-path: /Users/nanke/workSpace/uploadDir2/         #???????????????????????????????????????
    scan-interval: 30000                  #?? N ????????????????????????????????
  watch-mysql:
    enabled: true
    scan-interval: 300000                 #ms, ???????????????????1????
    data-row-limit: 1000                  #???????????????????????????
    file-row-limit: 1000                  #??????????????????????????
    user-row-limit: 1000                  #??????????????????

server:
  port: 7070

spring:
  profiles:
    active: druid
  elasticsearch:
    uris: http://127.0.0.1:9200/      #?????????
  ai:
    openai:     # OpenAI ???? OpenAI ????
      base-url: https://api.oaipro.com
      api-key: sk-ckUN5lhLOHXZzagggqAvTTKPhbU27a1K9gVZkHZK9UNxaavR #??????? key
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
        enabled: true
      enabled: true
    zhipuai:    #?????
      api-key: bf7faa05e59aa1a9e86a5829c60fa643.P5TqB2LGfg9hNH5C #??????? key
      chat:
        options:
          temperature: 0.7
          model: GLM-4-Plus
        enabled: true
      embedding:
        options:
          model: embedding-3            #?????????????? elasticsearch ??????????????
        enabled: true
      enabled: true
    ollama: # ?? Ollama ??????? llama3.2 ?? (?????????)
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
        enabled: true
    vectorstore:
      elasticsearch:
        initialize-schema: true         #????????
        index-name: mind-mark           #?? MindMark ??????????????
        dimensions: 2048                #?????????????????????????
        similarity: cosine
        batching-strategy: TOKEN_COUNT
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    root: DEBUG
    com.mindmark: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.engine.QueryParameters: DEBUG
    org.hibernate.engine.query.HQLQueryPlan: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
