application:
    name: MindMark
    version: 1.0.0-SNAPSHOT
    copyright-year: 2024
    demo-enabled: true
    address-enabled: true
    watch-file:
      enabled: true                         #是否开启文件监控功能，开启后会定时扫描目录中的数据，并进行嵌入操作
      file-path: C:/mindmark/upload         #文件上传目录，请根据自己服务器情况配置，定时任务会自动扫描这个目录进行嵌入操作
      scan-interval: 30000                  #每隔 N 秒扫描一次目录，监控发生变化的文件，注意大模型嵌入调用的费用问题
    watch-mysql:
      enabled: true
      scan-interval: 60000
      table: nicefish_cms_post

server:
  port: 9090

spring:
  profiles:
    active: druid
  elasticsearch:
    uris: http://192.168.0.105:9200/      #请改成你自己的路径
  ai:
    zhipuai:    #智谱大模型
      api-key:  #请改成你自己的 key
      chat:
        options:
          temperature: 0.7
          model: GLM-4-Plus
        enabled: true
      embedding:
        options:
          model: embedding-3               #嵌入模型的向量维度需要和下面 elasticsearch 的维度相同，否则无法写入数据
        enabled: true
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index           #TODO: 实现多租户模式，为每一个用户建立独立的索引
        dimensions: 2048                   #不要修改这个配置，与具体大模型本身的维度参数有关系
        similarity: cosine
        batching-strategy: TOKEN_COUNT

logging:
  level:
    root: TRACE
    com.mindmark: TRACE
    org.springframework: TRACE
    org.hibernate: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.QueryParameters: TRACE
    org.hibernate.engine.query.HQLQueryPlan: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
